### ISSUE TITLE
Binary releases?

### ISSUE THREAD

**Issue by mweibel** [ctcherry/tlself#3]
Hi,

this is exactly what I need and I contributed some things to improve usability of it. 
Hope you like the changes :) 

One other thing I thought of: add binary releases to the releases page. I'd happily contribute a PR to add that, too.. If you agree with it?

Thanks!

**Comment by ctcherry** [comment]
Hey thanks for the support and contributing! The PRs look great, I'll approve them shortly.

I'm supportive of binary releases, go for it!
